import { describe, expect, it } from "vitest";
import { projectTree } from "./geometry";
import { applyEntry, createTree, replayEntries, updateEntryStatus } from "./growth";
import type { Entry } from "./types";
function entries(count: number): Entry[] { return Array.from({ length: count }, (_, index) => ({ id: `e-${index + 1}`, text: `Entry ${index + 1}`, createdAt: index, status: "open" as const })); }
describe("V3 growth contract", () => {
  it("gives every entry one permanent chronological leaf identity", () => { const state = replayEntries("soul-a", entries(1000)); expect(state.leaves).toHaveLength(1000); expect(new Set(state.leaves.map((leaf) => leaf.entryId)).size).toBe(1000); expect(state.leaves[0].bornAtEvent).toBe(1); expect(state.leaves[999].bornAtEvent).toBe(1000); });
  it("is deterministic for the same soul and history", () => { const history = entries(300); expect(replayEntries("soul-a", history)).toEqual(replayEntries("soul-a", history)); });
  it("canonicalizes replay order instead of trusting database row order", () => { const history = entries(80); expect(replayEntries("soul-a", [...history].reverse())).toEqual(replayEntries("soul-a", history)); });
  it("keeps earlier developmental history unchanged when a new entry arrives", () => { const first = replayEntries("soul-a", entries(299)), next = applyEntry(first, entries(300)[299]); expect(next.modules.slice(0, first.modules.length)).toEqual(first.modules); expect(next.leaves.slice(0, first.leaves.length)).toEqual(first.leaves); });
  it("changes entry state without rewriting structural history", () => { const state = replayEntries("soul-a", entries(40)), completed = updateEntryStatus(state, "e-12", "completed"); expect(completed.modules).toEqual(state.modules); expect(completed.leaves.find((leaf) => leaf.entryId === "e-12")?.status).toBe("completed"); });
  it("derives present-day geometry without storing it in historical modules", () => { const young = replayEntries("soul-a", entries(30)), mature = replayEntries("soul-a", entries(1000)), youngGeometry = projectTree(young), matureGeometry = projectTree(mature); expect(young.modules[0]).not.toHaveProperty("start"); expect(young.modules[0]).not.toHaveProperty("thickness"); expect(mature.modules.slice(0, young.modules.length)).toEqual(young.modules); expect(matureGeometry[0].thickness).toBeGreaterThanOrEqual(youngGeometry[0].thickness); });
  it("projects a connected finite hierarchy", () => { const state = replayEntries("soul-a", entries(1000)), projected = projectTree(state), byId = new Map(projected.map((segment) => [segment.id, segment])); for (const segment of projected) { for (const value of [segment.start.x, segment.start.y, segment.end.x, segment.end.y, segment.heading, segment.length, segment.thickness]) expect(Number.isFinite(value)).toBe(true); if (segment.parentId) { const parent = byId.get(segment.parentId); expect(parent).toBeDefined(); expect(segment.start).toEqual(parent?.end); } } });
  it("uses sublinear structural growth at long histories", () => { const state = replayEntries("soul-a", entries(1000)); expect(state.modules.length).toBeLessThan(250); expect(state.modules.length).toBeGreaterThan(50); });
  it("allows different souls to develop different histories", () => { const history = entries(100); expect(replayEntries("soul-a", history).modules).not.toEqual(replayEntries("soul-b", history).modules); });
  it("does not add the same entry twice", () => { const entry = entries(1)[0], once = applyEntry(createTree("soul-a"), entry); expect(applyEntry(once, entry)).toEqual(once); });
  it("rejects silent historical insertion into a live tree tip", () => { const state = replayEntries("soul-a", [{ id: "a", text: "A", createdAt: 10, status: "open" }, { id: "b", text: "B", createdAt: 20, status: "open" }]); expect(() => applyEntry(state, { id: "older", text: "Older", createdAt: 15, status: "open" })).toThrow(/replay the canonical history/i); });
});
