import { projectTree } from "./geometry";
import { keyedRange } from "./random";
import { midpoint, pointFrom, pointToSegmentDistance, properIntersection } from "./spatial";
import { deriveTreeTraits, type TreeTraits } from "./traits";
import type { GrowthModule, GrowthRelation, Point, ProjectedSegment, TreeState } from "./types";
const TRUNK_AXIS = "axis-0", MAX_ORDER = 4, MIN_LATERAL_AGE = 3;
interface Candidate { parent: GrowthModule; relation: Exclude<GrowthRelation, "origin">; axisId: string; order: number; heading: number; length: number; score: number; }
interface Bounds { minX: number; maxX: number; minY: number; maxY: number; }
function structuralInterval(eventIndex:number):number{return Math.min(12,2+Math.floor(Math.log2(eventIndex+1)));}
export function shouldGrowStructure(eventIndex:number):boolean{return eventIndex<=14||eventIndex%structuralInterval(eventIndex)===0;}
function hasChild(state:TreeState,parentId:string,relation:Exclude<GrowthRelation,"origin">):boolean{return state.modules.some((module)=>module.parentId===parentId&&module.relation===relation);}
function latestAxisEvent(state:TreeState,axisId:string):number{let latest=0;for(const module of state.modules)if(module.axisId===axisId)latest=Math.max(latest,module.bornAtEvent);return latest;}
function latestLateralFromAxisEvent(state:TreeState,axisId:string):number{const byId=new Map(state.modules.map((module)=>[module.id,module]));let latest=0;for(const module of state.modules){if(module.relation!=="lateral"||!module.parentId)continue;const parent=byId.get(module.parentId);if(parent?.axisId===axisId)latest=Math.max(latest,module.bornAtEvent);}return latest;}
function axisModuleCount(state:TreeState,axisId:string):number{return state.modules.reduce((count,module)=>count+(module.axisId===axisId?1:0),0);}
function lateralFromAxisCount(state:TreeState,axisId:string):number{const byId=new Map(state.modules.map((module)=>[module.id,module]));let count=0;for(const module of state.modules){if(module.relation!=="lateral"||!module.parentId)continue;if(byId.get(module.parentId)?.axisId===axisId)count+=1;}return count;}
function preferredAxisModules(order:number,traits:TreeTraits):number{if(order===0){const normalized=(traits.apicalDominance-0.58)/Math.max(0.001,0.84-0.58);return 12+Math.max(0,Math.min(1,normalized))*4;}if(order===1)return 7;if(order===2)return 5;if(order===3)return 4;return 3;}
function boundsFor(segments:readonly ProjectedSegment[]):Bounds{let minX=0,maxX=0,minY=0,maxY=0;for(const s of segments){minX=Math.min(minX,s.start.x,s.end.x);maxX=Math.max(maxX,s.start.x,s.end.x);minY=Math.min(minY,s.start.y,s.end.y);maxY=Math.max(maxY,s.start.y,s.end.y);}return{minX,maxX,minY,maxY};}
function lengthRange(order:number):readonly[number,number]{if(order<=0)return[16,21];if(order===1)return[13,18];if(order===2)return[10,15];if(order===3)return[7.5,12];return[5.5,9];}
function candidateLength(state:TreeState,eventIndex:number,parent:GrowthModule,relation:Exclude<GrowthRelation,"origin">,order:number):number{const[min,max]=lengthRange(order),scale=relation==="continuation"?1:0.94;return keyedRange(state.soul,`structure:${eventIndex}:${parent.id}:${relation}:length`,min,max)*scale;}
function proposedClearance(start:Point,end:Point,parentId:string,segments:readonly ProjectedSegment[]):number{const mid=midpoint(start,end);let clearance=Number.POSITIVE_INFINITY;for(const segment of segments){if(segment.id===parentId)continue;clearance=Math.min(clearance,pointToSegmentDistance(mid,segment.start,segment.end),pointToSegmentDistance(end,segment.start,segment.end));}return Number.isFinite(clearance)?clearance:Math.hypot(end.x-start.x,end.y-start.y);}
function crossesExisting(start:Point,end:Point,parentId:string,segments:readonly ProjectedSegment[]):boolean{for(const segment of segments){if(segment.id===parentId)continue;if(properIntersection(start,end,segment.start,segment.end))return true;}return false;}
function predictedBounds(bounds:Bounds,end:Point):Bounds{return{minX:Math.min(bounds.minX,end.x),maxX:Math.max(bounds.maxX,end.x),minY:Math.min(bounds.minY,end.y),maxY:Math.max(bounds.maxY,end.y)};}
function crownScore(current:Bounds,proposedEnd:Point,traits:TreeTraits,moduleCount:number):number{if(moduleCount<8)return 0;const next=predictedBounds(current,proposedEnd),width=Math.max(1,next.maxX-next.minX),height=Math.max(1,next.maxY-next.minY),aspect=width/height,aspectError=Math.abs(aspect-traits.crownAspect),centre=(next.minX+next.maxX)/2,targetCentre=Math.tan((traits.lean*Math.PI)/180)*height*0.3,centreError=Math.abs(centre-targetCentre)/Math.max(30,height);return-aspectError*0.75-centreError*0.65;}
function baseVigor(relation:Exclude<GrowthRelation,"origin">,order:number,parentAge:number,traits:TreeTraits):number{if(relation==="continuation")return 1.28+(traits.apicalDominance*1.35)/(1+order*0.68);const budAge=Math.max(0,parentAge-MIN_LATERAL_AGE),readiness=Math.min(2.1,budAge*0.16);return 1.05+(1-traits.apicalDominance)*0.8+readiness-order*0.12;}
function architectureScore(state:TreeState,candidate:Omit<Candidate,"score">,traits:TreeTraits):number{const axisModules=axisModuleCount(state,candidate.parent.axisId);if(candidate.relation==="continuation"){const establishmentBonus=Math.max(0,4-axisModules)*0.45,elongationPenalty=Math.max(0,axisModules-preferredAxisModules(candidate.order,traits))*0.24;return establishmentBonus-elongationPenalty;}const laterals=lateralFromAxisCount(state,candidate.parent.axisId),branchDensity=laterals/Math.max(1,axisModules-1);return-branchDensity*3.5;}
function scoreCandidate(state:TreeState,eventIndex:number,candidate:Omit<Candidate,"score">,segments:readonly ProjectedSegment[],projectedById:ReadonlyMap<string,ProjectedSegment>,bounds:Bounds,traits:TreeTraits):Candidate|null{const parent=projectedById.get(candidate.parent.id);if(!parent)return null;const start=parent.end,end=pointFrom(start,candidate.heading,candidate.length);if(!Number.isFinite(end.x)||!Number.isFinite(end.y)||end.y>0||candidate.length<=0.5||crossesExisting(start,end,candidate.parent.id,segments))return null;const clearance=proposedClearance(start,end,candidate.parent.id,segments);if(clearance<1.6)return null;const parentAge=state.growthIndex-candidate.parent.bornAtEvent,spaceScore=Math.min(1.5,clearance/Math.max(4,candidate.length*0.45)),lastRelatedGrowth=candidate.relation==="continuation"?latestAxisEvent(state,candidate.parent.axisId):latestLateralFromAxisEvent(state,candidate.parent.axisId),growthGap=lastRelatedGrowth===0?Number.POSITIVE_INFINITY:eventIndex-lastRelatedGrowth,recencyPenalty=growthGap>=3?0:(3-growthGap)*0.42,jitter=keyedRange(state.soul,`structure:${eventIndex}:${candidate.parent.id}:${candidate.relation}:${candidate.heading}:jitter`,-0.12,0.12),score=baseVigor(candidate.relation,candidate.order,parentAge,traits)+spaceScore*0.9+crownScore(bounds,end,traits,state.modules.length)+architectureScore(state,candidate,traits)-recencyPenalty+jitter;return{...candidate,score};}
function continuationCandidates(state:TreeState,eventIndex:number,segments:readonly ProjectedSegment[],projectedById:ReadonlyMap<string,ProjectedSegment>,bounds:Bounds,traits:TreeTraits):Candidate[]{const result:Candidate[]=[];for(const parent of state.modules){if(parent.order>MAX_ORDER||hasChild(state,parent.id,"continuation"))continue;const projection=projectedById.get(parent.id);if(!projection)continue;const targetHeading=parent.order===0?traits.lean:projection.heading*0.98,tropism=(targetHeading-projection.heading)*(parent.order===0?0.16:0.04),localNoise=keyedRange(state.soul,`structure:${eventIndex}:${parent.id}:continue:curve`,-traits.curvature,traits.curvature),baseHeading=projection.heading+tropism+localNoise*0.32,offsets=[-traits.curvature*0.9,0,traits.curvature*0.9],length=candidateLength(state,eventIndex,parent,"continuation",parent.order);for(const offset of offsets){const heading=Math.max(-80,Math.min(80,baseHeading+offset)),scored=scoreCandidate(state,eventIndex,{parent,relation:"continuation",axisId:parent.axisId,order:parent.order,heading,length},segments,projectedById,bounds,traits);if(scored)result.push(scored);}}return result;}
function lateralCandidates(state:TreeState,eventIndex:number,segments:readonly ProjectedSegment[],projectedById:ReadonlyMap<string,ProjectedSegment>,bounds:Bounds,traits:TreeTraits):Candidate[]{const result:Candidate[]=[];for(const parent of state.modules){if(parent.order>=MAX_ORDER||hasChild(state,parent.id,"lateral")||!hasChild(state,parent.id,"continuation")||state.growthIndex-parent.bornAtEvent<MIN_LATERAL_AGE)continue;const projection=projectedById.get(parent.id);if(!projection)continue;const order=parent.order+1,angleScale=keyedRange(state.soul,`structure:${eventIndex}:${parent.id}:lateral:angle-scale`,0.9,1.1),divergence=traits.branchAngle*angleScale,length=candidateLength(state,eventIndex,parent,"lateral",order);for(const side of[-1,1]as const){const rawHeading=projection.heading+side*divergence,heading=Math.max(-80,Math.min(80,rawHeading*0.96)),scored=scoreCandidate(state,eventIndex,{parent,relation:"lateral",axisId:`axis-${eventIndex}`,order,heading,length},segments,projectedById,bounds,traits);if(scored)result.push(scored);}}return result;}
function initialModule(state:TreeState,eventIndex:number,traits:TreeTraits):GrowthModule{return{id:`m-${eventIndex}`,parentId:null,axisId:TRUNK_AXIS,relation:"origin",order:0,bornAtEvent:eventIndex,restTurn:traits.lean*0.38+keyedRange(state.soul,`structure:${eventIndex}:origin:turn`,-1.2,1.2),restLength:keyedRange(state.soul,`structure:${eventIndex}:origin:length`,21,25)};}
export function growStructuralEvent(state:TreeState,eventIndex:number):GrowthModule|null{const traits=deriveTreeTraits(state.soul);if(state.modules.length===0)return initialModule(state,eventIndex,traits);if(!shouldGrowStructure(eventIndex))return null;const segments=projectTree(state),projectedById=new Map(segments.map((segment)=>[segment.id,segment])),bounds=boundsFor(segments);let candidates=continuationCandidates(state,eventIndex,segments,projectedById,bounds,traits);if(eventIndex>5)candidates=candidates.concat(lateralCandidates(state,eventIndex,segments,projectedById,bounds,traits));else candidates=candidates.filter((candidate)=>candidate.relation==="continuation"&&candidate.parent.axisId===TRUNK_AXIS);candidates.sort((a,b)=>b.score-a.score||a.order-b.order||a.parent.id.localeCompare(b.parent.id)||a.heading-b.heading);const winner=candidates[0];if(!winner)return null;const parentProjection=projectedById.get(winner.parent.id);if(!parentProjection)return null;return{id:`m-${eventIndex}`,parentId:winner.parent.id,axisId:winner.axisId,relation:winner.relation,order:winner.order,bornAtEvent:eventIndex,restTurn:winner.heading-parentProjection.heading,restLength:winner.length};}
